name: Build and Push Model

on:
  workflow_dispatch:
    inputs:
      stock:
        description: 'Stock'
        required: true
        default: 'AAPL'
      lstm_units_1:
        description: 'lstm units 1'
        required: true
        default: 10
      lstm_units_2:
        description: 'lstm units 2'
        required: true
        default: 20
      lstm_units_3:
        description: 'lstm units 3'
        required: true
        default: 30

jobs:
  train:
    runs-on: ubuntu-latest
    env:
        CLEARML_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        CLEARML_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
        LSTM_UNITS_1: ${{ github.event.inputs.lstm_units_1 }}
        LSTM_UNITS_2: ${{ github.event.inputs.lstm_units_2 }}
        LSTM_UNITS_3: ${{ github.event.inputs.lstm_units_3 }}
        STOCK: ${{ github.event.inputs.stock }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Train model with ClearML
      run: |
        python3 build-model.py
