name: Build and Push Model

on:
  push:
    branches:
      - master  # or your default branch
      
jobs:
  train:
    runs-on: ubuntu-latest
    env:
        CLEARML_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        CLEARML_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Train model with ClearML
      run: |
        python3 build-model.py
