name: Build and Push Model

on:
  workflow_dispatch:
    inputs:
      stock:
        description: 'Stock'
        required: true
        default: 'AAPL'
      lstm_units_1:
        description: 'LSTM Units 1 (suggested: 50, 100, 150, 200, 256, 512)'
        required: true
        default: 50
      lstm_units_2:
        description: 'LSTM Units 2 (suggested: 50, 100, 150, 200, 256, 512)'
        required: true
        default: 100
      lstm_units_3:
        description: 'LSTM Units 3 (suggested: 50, 100, 150, 200, 256, 512)'
        required: true
        default: 150
      epochs:
        description: 'Epochs (suggested: 10, 50, 100, 200, 500, 1000)'
        required: true
        default: 100
      batch_size:
        description: 'Batch Size (suggested: 16, 32, 64, 128, 256)'
        required: true
        default: 32



jobs:
  train:
    runs-on: ubuntu-latest
    env:
        CLEARML_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        CLEARML_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
        LSTM_UNITS_1: ${{ github.event.inputs.lstm_units_1 }}
        LSTM_UNITS_2: ${{ github.event.inputs.lstm_units_2 }}
        LSTM_UNITS_3: ${{ github.event.inputs.lstm_units_3 }}
        STOCK: ${{ github.event.inputs.stock }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Train model with ClearML
      run: |
        python3 build-model.py
