name: Train Model with ClearML

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Train model with ClearML
      run: |
        export CLEARML_API_KEY=${{ secrets.CLEARML_API_KEY }}
        python your_training_script.py
