name: Train Model with ClearML

on:
  push:
    branches:
      - master  # or your default branch


      
jobs:
  train:
    runs-on: ubuntu-latest
    env:
      CLEARML_API_KEY: ${{ secrets.CLEARML_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Train model with ClearML
      run: |
        python3 ml-pipeline.py
